// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zippo_Manage.Models;

#nullable disable

namespace Zippo_Manage.Migrations
{
    [DbContext(typeof(QLyZIPPOContext))]
    [Migration("20241226073004_AddFieldsToGiohang")]
    partial class AddFieldsToGiohang
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Zippo_Manage.Models.ChiTietDonHang", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaSP")
                        .IsFixedLength();

                    b.Property<string>("MaDh")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaDH")
                        .IsFixedLength();

                    b.Property<double>("DonGia")
                        .HasColumnType("float");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<double>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float")
                        .HasComputedColumnSql("([SoLuong]*[DonGia])", true);

                    b.HasKey("MaSp", "MaDh")
                        .HasName("PK__ChiTietD__2557507A23F2F6BC");

                    b.HasIndex("MaDh");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("Zippo_Manage.Models.ChiTietGioHang", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaSP")
                        .IsFixedLength();

                    b.Property<string>("MaGh")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaGH")
                        .IsFixedLength();

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<double>("TongCong")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("float")
                        .HasComputedColumnSql("([SoLuong]*[Gia])", true);

                    b.HasKey("MaSp", "MaGh")
                        .HasName("PK__ChiTietG__655752F4807AFB6F");

                    b.HasIndex("MaGh");

                    b.ToTable("ChiTietGioHang", (string)null);
                });

            modelBuilder.Entity("Zippo_Manage.Models.Donhang", b =>
                {
                    b.Property<string>("MaDh")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaDH")
                        .IsFixedLength();

                    b.Property<string>("MaKh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaKH")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayDatHang")
                        .HasColumnType("datetime");

                    b.HasKey("MaDh")
                        .HasName("PK__DONHANG__27258661D34B6D5A");

                    b.HasIndex("MaKh");

                    b.ToTable("DONHANG", (string)null);
                });

            modelBuilder.Entity("Zippo_Manage.Models.Giohang", b =>
                {
                    b.Property<string>("MaGh")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaGH")
                        .IsFixedLength();

                    b.Property<double>("Gia")
                        .HasColumnType("float");

                    b.Property<string>("MaKh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaKH")
                        .IsFixedLength();

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime");

                    b.Property<string>("SanphamMaSp")
                        .HasColumnType("nchar(10)");

                    b.Property<int>("SoLuongMua")
                        .HasColumnType("int");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("MaGh")
                        .HasName("PK__GIOHANG__2725AE85FFCB73F6");

                    b.HasIndex("MaKh");

                    b.HasIndex("SanphamMaSp");

                    b.ToTable("GIOHANG", (string)null);
                });

            modelBuilder.Entity("Zippo_Manage.Models.Khachhang", b =>
                {
                    b.Property<string>("MaKh")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaKH")
                        .IsFixedLength();

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoLot")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("SDT");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("MaKh")
                        .HasName("PK__KHACHHAN__2725CF1E34D722F2");

                    b.ToTable("KHACHHANG", (string)null);
                });

            modelBuilder.Entity("Zippo_Manage.Models.Loaisanpham", b =>
                {
                    b.Property<string>("MaLoai")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("TenLoai")
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .IsFixedLength();

                    b.HasKey("MaLoai")
                        .HasName("PK__LOAISANP__730A5759A4B8E1BF");

                    b.ToTable("LOAISANPHAM", (string)null);
                });

            modelBuilder.Entity("Zippo_Manage.Models.Sanpham", b =>
                {
                    b.Property<string>("MaSp")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaSP")
                        .IsFixedLength();

                    b.Property<double?>("Gia")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaLoai")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .IsFixedLength();

                    b.Property<string>("MotaSp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("MotaSP");

                    b.Property<int?>("SoLuong")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("TenSp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("TenSP");

                    b.HasKey("MaSp")
                        .HasName("PK__SANPHAM__2725081C5810BFAB");

                    b.HasIndex("MaLoai");

                    b.ToTable("SANPHAM", (string)null);
                });

            modelBuilder.Entity("Zippo_Manage.Models.Taikhoan", b =>
                {
                    b.Property<string>("MaTk")
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaTK")
                        .IsFixedLength();

                    b.Property<string>("MaKh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("MaKH")
                        .IsFixedLength();

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Ngaytao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Vaitro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaTk")
                        .HasName("PK__TAIKHOAN__2725007093B5CB48");

                    b.HasIndex("MaKh");

                    b.ToTable("TAIKHOAN", (string)null);
                });

            modelBuilder.Entity("Zippo_Manage.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("Zippo_Manage.Models.Donhang", "MaDhNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDh")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDon__MaDH__48CFD27E");

                    b.HasOne("Zippo_Manage.Models.Sanpham", "MaSpNavigation")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietDon__MaSP__47DBAE45");

                    b.Navigation("MaDhNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("Zippo_Manage.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("Zippo_Manage.Models.Giohang", "MaGhNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGh")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietGio__MaGH__4CA06362");

                    b.HasOne("Zippo_Manage.Models.Sanpham", "MaSpNavigation")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaSp")
                        .IsRequired()
                        .HasConstraintName("FK__ChiTietGio__MaSP__4BAC3F29");

                    b.Navigation("MaGhNavigation");

                    b.Navigation("MaSpNavigation");
                });

            modelBuilder.Entity("Zippo_Manage.Models.Donhang", b =>
                {
                    b.HasOne("Zippo_Manage.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Donhangs")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__DONHANG__MaKH__4222D4EF");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("Zippo_Manage.Models.Giohang", b =>
                {
                    b.HasOne("Zippo_Manage.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Giohangs")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__GIOHANG__MaKH__44FF419A");

                    b.HasOne("Zippo_Manage.Models.Sanpham", "Sanpham")
                        .WithMany()
                        .HasForeignKey("SanphamMaSp");

                    b.Navigation("MaKhNavigation");

                    b.Navigation("Sanpham");
                });

            modelBuilder.Entity("Zippo_Manage.Models.Sanpham", b =>
                {
                    b.HasOne("Zippo_Manage.Models.Loaisanpham", "MaLoaiNavigation")
                        .WithMany("Sanphams")
                        .HasForeignKey("MaLoai")
                        .HasConstraintName("FK__SANPHAM__MaLoai__3F466844");

                    b.Navigation("MaLoaiNavigation");
                });

            modelBuilder.Entity("Zippo_Manage.Models.Taikhoan", b =>
                {
                    b.HasOne("Zippo_Manage.Models.Khachhang", "MaKhNavigation")
                        .WithMany("Taikhoans")
                        .HasForeignKey("MaKh")
                        .IsRequired()
                        .HasConstraintName("FK__TAIKHOAN__MaKH__3A81B327");

                    b.Navigation("MaKhNavigation");
                });

            modelBuilder.Entity("Zippo_Manage.Models.Donhang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("Zippo_Manage.Models.Giohang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("Zippo_Manage.Models.Khachhang", b =>
                {
                    b.Navigation("Donhangs");

                    b.Navigation("Giohangs");

                    b.Navigation("Taikhoans");
                });

            modelBuilder.Entity("Zippo_Manage.Models.Loaisanpham", b =>
                {
                    b.Navigation("Sanphams");
                });

            modelBuilder.Entity("Zippo_Manage.Models.Sanpham", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("ChiTietGioHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
